Vagrant.configure(2) do |config|
  config.vm.box = 'flatcar-linux-2512.2-amd64'

  config.vm.hostname = 'example.test'

  config.vm.provider 'libvirt' do |lv, config|
    lv.default_prefix = "#{File.basename(File.dirname(File.dirname(__FILE__)))}_"
    lv.memory = 2*1024
    lv.cpus = 2
    lv.cpu_mode = 'host-passthrough'
    lv.nested = false
    lv.keymap = 'pt'
  end

  config.vm.provision 'shell', inline: 'uname -a'
  config.vm.provision 'shell', inline: 'cat /etc/os-release'
  config.vm.provision 'shell', inline: 'lsblk -x KNAME -o KNAME,SIZE,TRAN,SUBSYSTEMS,FSTYPE,UUID,LABEL,MODEL,SERIAL'
  config.vm.provision 'shell', inline: 'df -h'
end
